### ISSUE TITLE
Fatal error when loaded without Picker Dollies

### ISSUE THREAD

**Issue by Saklad5** [modo-lv/factorio-mod-stack-combinator#35]
I’m getting the following error when I try to load any game with Stack Combinator installed:
`Unknown custom-input name: dolly-rotate-rectangle
stack traceback:
	[C]: in function 'on_event'
	__stdlib__/stdlib/event/event.lua:156: in function 'register'
	__stack-combinator__/scripts/other-mods/picker-dollies.lua:44: in function 'register_all'
	__stack-combinator__/control.lua:15: in main chunk`

It seems that you are bypassing the code that actually checks whether Picker Dollies is installed by calling the `register_all` function directly from control.lua.

**Comment by modo-lv** [comment]
Thanks for the report, the bug is fixed and version 1.2.3 uploaded to mod portal.
