### ISSUE TITLE
Error joining multiplayer server

### ISSUE THREAD

**Issue by Laremere** [modo-lv/factorio-mod-stack-combinator#36]
We're sometimes able to join, and it seems to be better if we have just restarted the server, but we keep hitting it when we join later:

![20210324201345_1](https://user-images.githubusercontent.com/202599/112413703-e1ddc280-8cdd-11eb-891e-8e192151b1d9.jpg)

From the log:
`
 124.370 Error ClientMultiplayerManager.cpp:1116: mod-stack-combinator was registered for the following events when the map was saved but has not re-registered them as a result of loading: dolly-rotate-rectangle (ID 182) and Custom event (ID 249)
 124.370 Error ClientMultiplayerManager.cpp:98: MultiplayerManager failed: "" + multiplayer.script-event-mismatch + "
" + "
mod-stack-combinator"`

**Comment by modo-lv** [comment]
I've fixed what I think was the problem, but since I can't test multiplayer on my own, do you mind testing this out for me before I upload to the mod portal?
[stack-combinator_1.2.4.zip](https://github.com/modo-lv/factorio-mod-stack-combinator/files/6204257/stack-combinator_1.2.4.zip)

**Comment by Laremere** [comment]
Yeah that seems to work, thanks!

**Comment by modo-lv** [comment]
Fixed in 1.2.4.
