### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by schoos76** [modo-lv/factorio-mod-stack-combinator#37]
Hi, 

i'm just trying this mod for the first time and currently using it in a setup for my LTN based supply for my outposts: A Ghost Scanner  in the outpost and I think 2 stack combinators - one for rounding up to stack size, one in a chain of combinators to store a list of all entities that were requested via LTN to keep some basic inventory for quick repairs. I'm maybe having 15 of those setups at the moment and I'm sur;prised about the 3 ms the update for the stack combinator needs per tick.
![image](https://user-images.githubusercontent.com/4555004/123499649-c7174300-d66a-11eb-8d19-470e22abbf84.png)
 
Any way to improve this performance a bit?

**Comment by modo-lv** [comment]
I haven't encountered any noticeable slowdown in my playing, even with ~30 StaCos running, but I haven't looked at the timings in depth. I will explore more when I get some free time.

Can you provide your save file?

**Comment by schoos76** [comment]
Just to be sure to get the spin correct: I'm surprised to see this 3something ms per tick for the StaCo mod and am wondering if this could be improved and am wondering how this will scale when there's more StaCo in the long run. I'm not sure whether my slight drop in FPS/UPS (57 instead of 60) is caused by StaCo - but well, those 3 ms cought my eyes. 

Save (a bit advanced compared to the initial post) is available at https://www.dropbox.com/s/yecxn4p91hlgjzc/RW9.zip?dl=0

**Comment by djarbz** [comment]
I have 186 of these deployed and I am noticing ~18ish ms on this mod, which is over half of my update time of 32ms.
That comes to ~1ms/10 StaCo.
I was running 55-60FPS/UPS prior to deploying these.
I love the mod, but that is quite a performance hit.

**Comment by schoos76** [comment]
I was reading a bit through the code and also some LUA guides on performance, and I think the stackify function could use some optimitation - it must be in the run() function and stackify is - as far as I can see - the workhorse for that.

At least once for every staco, we're building up a (in my case) 40 element table in line 102 (and the for loop) of the staco.lua and that triggers 5 or 6 rehashes for the tables - for every stack every tick. And accoridng to https://www.lua.org/gems/sample.pdf this might be an expensive operation in terms of CPU cycles. 

Wouldn't it be reasonable to initialize result = result or input in line 64? With that we could get down the number of rehashes quite a bit, at least in those cases where we have evenly populated input on both red and green wires resp. when we start with the correct wire? Still not optimal for the case that we have 1 signal on the first wire color that's processed and 40 on the other. 

Maybe it's even more reasonable to already pre-initialize the result table in around line 26 of staco.lua as the superset of both red and green signals to the appropriate size (and maybe keys).

**Comment by djarbz** [comment]
That definitely sounds like a good idea.

In my case, I have 1 item type on 1 wire, I'm just trying to calculate how many stacks so I can tell the station how many trains to call.

**Comment by modo-lv** [comment]
There doesn't appear to be any way to dynamically set the size of a table before adding elements to it. The only way I could find was by using a meta table:

```lua
  local size = ((red and #red.signals) or 0) + ((green and #green.signals) or 0)
  setmetatable(result, {
    __len = function() return size end
  })

  result = self.stackify(red, self.config.invert_red, op, result)
  result = self.stackify(green, self.config.invert_green, op, result)
```

But that made performance worse, not improve it. So far the only way I've found to reliably improve performance is the most basic option — not update every tick. Updating every other tick predictably cuts the processing time by 50%, but I don't know how breaking such a change would be for existing setups (and it would have to be a configurable setting anyway).

If anyone can think of any other way to improve the performance without reducing update frequency, comments/PRs are welcome. I myself am out of ideas.

**Comment by djarbz** [comment]
@modo-lv first of all, thank you for looking into this and creating an awesome mod!

As far as updating every X amounts of ticks, this is going to measure contents of something, which can only update as fast as an inserter can transfer correct? So in theory, we could update once per inserter cycle? Maybe twice?

**Comment by modo-lv** [comment]
Using items is the most common use case, but I can't assume that everyone will use it that way. Circuit networks can get very complicated and not be dependent on actual item insertion at all (especially when considering other mods). To best address the issue right now, I have published a new version, 1.2.8 that includes a runtime setting for signal processing delays.

Ideally I would also like to add the option to individual combinators, so that you can adjust each combinator in addition to having a global setting, but I don't know when I'll have the time.

**Comment by djarbz** [comment]
Thanks, I'll try it out. I'm currently only using it for train stops, so I don't need a fast update time.
Just a thought, might be worthwhile to try updating only a fraction of them per tick?

**Comment by modo-lv** [comment]
Fractional updates in combination with update delays (>0 ticks) could increase performance, but I have a feeling it would be quite tricky to implement consistently. But I'll consider it.

**Comment by djarbz** [comment]
I just launched with your new version, went from about 11ms to 2ms using a 5 tick delay.
I'll let you know if I notice any issues.
I'm also tried lowering max signals to 20, but I actually saw a slight drop in performance.

As for the fractional update, I'm thinking if you could take an input setting, like the delay setting, and take 1/X of the length of the array every tick. Each tick move to the next set of 1/X until you wrap around. I'm not sure if it's possible to track a variable that doesn't get initialized/reset every tick trigger to count the number of iterations?

**Comment by modo-lv** [comment]
The question with the fractional update is whether it will actually improve performance compared to a simple delay. Updating 20 StaCos every 10 ticks is the same total amount of processing (and same update delay) as updating 2 StaCos every tick — performance depends on how the game handles the different approaches. And fractional updates are complicated to implement, it's not worth doing it if there's no real performance gain.

But I've added it as a separate issue to look into: https://github.com/modo-lv/factorio-mod-stack-combinator/issues/38

**Comment by djarbz** [comment]
That absolutely makes sense.
