### ISSUE TITLE
(1.2.10) caused a non-recoverable error

### ISSUE THREAD

**Issue by francoisdejgr** [modo-lv/factorio-mod-stack-combinator#41]
The mod Stack Combinator (1.2.10) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event stack-combinator::on_load()
Detected modifications to the 'global' table:
CRC before: 3756198672
CRC after: 4232860096.
This indicates the mod is not save/load stable and not multiplayer safe.
on_load() should never change the global table.

If you want a save file - I can provide

**Comment by modo-lv** [comment]
I don't have time to playstest right now, but if I'm right, the fix should be just one line. Could you test this and let me know if it solves the problem?
[stack-combinator_1.2.11.zip](https://github.com/modo-lv/factorio-mod-stack-combinator/files/7020161/stack-combinator_1.2.11.zip)

**Comment by francoisdejgr** [comment]
Greetings

I have downloaded the file and placed it in my mod folder but the system is not seeing it.
Will try to load and advise
Thx for quick response

Regards

**Comment by modo-lv** [comment]
I've uploaded the 1.2.11 version on the mod portal, you should be able to update normally.
